# Generated by Django 6.0.2 on 2026-02-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sessionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('OPEN', 'Open (Pay at end)'), ('PREPAID', 'Pre-paid (Fixed time)')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='prepaid_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
