# Generated by Django 6.0.2 on 2026-02-08 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_mode_session_prepaid_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказ товара', 'verbose_name_plural': 'Заказы товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterModelOptions(
            name='resourceusage',
            options={'verbose_name': 'Использование товара', 'verbose_name_plural': 'Использование товаров'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AlterModelOptions(
            name='sessionitem',
            options={'verbose_name': 'Товар сессии', 'verbose_name_plural': 'Товары сессии'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('billiard', 'Бильярд'), ('sony', 'Sony')], max_length=20),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('end_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
