# Generated by Django 6.0.2 on 2026-02-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bill_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена закупа'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='closed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Закрыто в'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во товара'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('billiard', 'Бильярд'), ('sony', 'Sony')], max_length=20, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закончено'),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resource', verbose_name='Стол'),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начато'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закончено'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('OPEN', 'Open (Pay at end)'), ('PREPAID', 'Pre-paid (Fixed time)')], default='OPEN', max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='session',
            name='prepaid_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='session',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.resource', verbose_name='Стол'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начато'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при заказе'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='sessionitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец(время)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Изначальная сумма'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало(время)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
