# Generated by Django 6.0.2 on 2026-02-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shift_options_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionitem',
            options={'ordering': ['id'], 'verbose_name': 'Товар сессии', 'verbose_name_plural': 'Товары сессии'},
        ),
    ]
