# Generated by Django 6.0.2 on 2026-02-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sessionitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.shift', verbose_name='Смена'),
        ),
    ]
