# Generated by Django 6.0.2 on 2026-02-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_session_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('OPEN', 'Открыть (Оплата в конце)'), ('PREPAID', 'Предоплата (фиксированное время)')], default='OPEN', max_length=10, verbose_name='Вид'),
        ),
    ]
