# Generated by Django 6.0.2 on 2026-02-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_session_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('billiard', 'Бильярд'), ('sony', 'Sony'), ('bar', 'Бар')], max_length=20, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('OPEN', 'Открыть (Оплата в конце)'), ('PREPAID', 'Предоплата (фиксированное время)'), ('BAR', 'Счет для бара(без вермени)')], default='OPEN', max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='session',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.resource', verbose_name='Стол'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('type', models.CharField(choices=[('addition', 'Приход (Доставка)'), ('correction', 'Коррекция (Инвентаризация)'), ('waste', 'Списание (Брак/Разлив)')], max_length=20, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.shift')),
            ],
        ),
    ]
