# Generated by Django 6.0.2 on 2026-02-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_resource_type_alter_session_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Движение товара', 'verbose_name_plural': 'Движения товаров'},
        ),
        migrations.AddField(
            model_name='session',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.shift', verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('addition', 'Приход (Доставка)'), ('correction', 'Коррекция (Инвентаризация)'), ('waste', 'Списание (Брак/Разлив)')], max_length=20, verbose_name='Тип движения'),
        ),
        migrations.CreateModel(
            name='SessionPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='core.session')),
            ],
            options={
                'verbose_name': 'Пауза сессии',
                'verbose_name_plural': 'Паузы сессий',
            },
        ),
    ]
