# Generated by Django 6.0.2 on 2026-06-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_stockmovement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен (продается)'),
        ),
    ]
