# Generated by Django 6.0.2 on 2026-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sessionitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('QR', 'QR')], default='CASH', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
